// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp';
export type { RuntimeConfig } from './core/defineApp';
// plugins
export { getSketchJSON } from 'D:/resin-hooks/.dumi/tmp/plugin-html2sketch';
// plugins types.d.ts
// @umijs/renderer-*
export {
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  Helmet,
  HelmetProvider,
  createSearchParams,
  generatePath,
  matchPath,
  matchRoutes,
  Navigate,
  NavLink,
  Outlet,
  resolvePath,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRoutes,
  useSearchParams,
  useAppData,
  useClientLoaderData,
  useLoaderData,
  useRouteProps,
  useSelectedRoutes,
  useServerLoaderData,
  renderClient,
  __getRoot,
  Link,
  useRouteData,
  __useFetcher,
  withRouter,
} from 'D:/resin-hooks/node_modules/.pnpm/@umijs+renderer-react@4.6.2_ea16bafe81ebfb85e709c3eb98271dca/node_modules/@umijs/renderer-react';
export type {
  History,
  ClientLoader,
} from 'D:/resin-hooks/node_modules/.pnpm/@umijs+renderer-react@4.6.2_ea16bafe81ebfb85e709c3eb98271dca/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export {
  ApplyPluginsType,
  PluginManager,
} from 'D:/resin-hooks/node_modules/.pnpm/umi@4.6.23_@babel+core@7.28_be6d8fe5b77a1fa0392c2d1b863f46eb/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
