// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/resin-hooks/node_modules/.pnpm/dumi@2.3.1_@babel+core@7.28_b31270949a0956788da3a59703e8b37e/node_modules/dumi/theme-default/builtins/API/index.js';
